# recipe_gbrt_scalar_diagnostics_austral_jet.yml
---
documentation:

  description: |
    Use inter-model GBRT (Gradient Boosted Regression Trees) model to predict
    future climate for scalar diagnostics.

  authors:
    - schl_ma

  references:
    null

  projects:
    - crescendo


datasets:
  - {dataset: ACCESS1-0,      ensemble: r1i1p1}
  - {dataset: ACCESS1-3,      ensemble: r1i1p1}


  # - {dataset: bcc-csm1-1,     ensemble: r1i1p1}


  # - {dataset: BNU-ESM,        ensemble: r1i1p1}
  # - {dataset: CanESM2,        ensemble: r1i1p1}
  # - {dataset: CanESM2,        ensemble: r2i1p1}
  # - {dataset: CanESM2,        ensemble: r3i1p1}
  # - {dataset: CanESM2,        ensemble: r4i1p1}
  # - {dataset: CanESM2,        ensemble: r5i1p1}


  # - {dataset: CCSM4,          ensemble: r1i1p1}
  # - {dataset: CCSM4,          ensemble: r2i1p1}
  # - {dataset: CCSM4,          ensemble: r3i1p1}
  # - {dataset: CCSM4,          ensemble: r4i1p1}
  # - {dataset: CCSM4,          ensemble: r5i1p1}
  # - {dataset: CCSM4,          ensemble: r6i1p1}


  # - {dataset: CESM1-BGC,      ensemble: r1i1p1}
  # - {dataset: CESM1-CAM5,     ensemble: r1i1p1}
  # - {dataset: CESM1-CAM5,     ensemble: r2i1p1}
  # - {dataset: CESM1-CAM5,     ensemble: r3i1p1}
  # - {dataset: CMCC-CMS,       ensemble: r1i1p1}
  # - {dataset: CNRM-CM5,       ensemble: r1i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r1i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r2i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r3i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r4i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r5i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r6i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r7i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r8i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r9i1p1}
  # - {dataset: CSIRO-Mk3-6-0,  ensemble: r10i1p1}
  # - {dataset: GFDL-CM3,       ensemble: r1i1p1}
  # - {dataset: GFDL-ESM2G,     ensemble: r1i1p1}
  # - {dataset: GFDL-ESM2M,     ensemble: r1i1p1}
  # - {dataset: HadGEM2-AO,     ensemble: r1i1p1}
  # - {dataset: inmcm4,         ensemble: r1i1p1}
  # - {dataset: IPSL-CM5A-LR,   ensemble: r1i1p1}
  # - {dataset: IPSL-CM5A-LR,   ensemble: r2i1p1}
  # - {dataset: IPSL-CM5A-LR,   ensemble: r3i1p1}
  # - {dataset: IPSL-CM5A-LR,   ensemble: r4i1p1}
  # - {dataset: IPSL-CM5A-MR,   ensemble: r1i1p1}
  # - {dataset: IPSL-CM5B-LR,   ensemble: r1i1p1}
  # - {dataset: MIROC5,         ensemble: r1i1p1}
  # - {dataset: MIROC5,         ensemble: r2i1p1}
  # - {dataset: MIROC-ESM,      ensemble: r1i1p1}
  # - {dataset: MIROC-ESM-CHEM, ensemble: r1i1p1}
  # - {dataset: MPI-ESM-LR,     ensemble: r1i1p1}
  # - {dataset: MPI-ESM-LR,     ensemble: r2i1p1}
  # - {dataset: MPI-ESM-LR,     ensemble: r3i1p1}
  # - {dataset: MPI-ESM-MR,     ensemble: r1i1p1}
  # - {dataset: MPI-ESM-MR,     ensemble: r2i1p1}
  # - {dataset: MPI-ESM-MR,     ensemble: r3i1p1}
  # - {dataset: MRI-CGCM3,      ensemble: r1i1p1}
  # - {dataset: NorESM1-M,      ensemble: r1i1p1}


preprocessors:

  noop:
    {}

  time_average:
    time_average: null

  sp50: &sp50
    extract_levels:
      levels: 5000
      scheme: linear
    extract_region:
      start_latitude: -90
      end_latitude: -60
      start_longitude: 0
      end_longitude: 360
    average_region:
      coord1: latitude
      coord2: longitude

  sp100: &sp100
    extract_levels:
      levels: 10000
      scheme: linear
    extract_region:
      start_latitude: -90
      end_latitude: -60
      start_longitude: 0
      end_longitude: 360
    average_region:
      coord1: latitude
      coord2: longitude

  ng50: &ng50
    extract_levels:
      levels: 5000
      scheme: linear
    extract_region:
      start_latitude: -82.5
      end_latitude: 82.5
      start_longitude: 0
      end_longitude: 360
    average_region:
      coord1: latitude
      coord2: longitude

  ng100: &ng100
    extract_levels:
      levels: 10000
      scheme: linear
    extract_region:
      start_latitude: -90
      end_latitude: 90
      start_longitude: 0
      end_longitude: 360
    average_region:
      coord1: latitude
      coord2: longitude

  trop250: &trop250
    extract_levels:
      levels: 25000
      scheme: linear
    extract_region:
      start_latitude: -30
      end_latitude: 30
      start_longitude: 0
      end_longitude: 360
    average_region:
      coord1: latitude
      coord2: longitude


diagnostics:

  diag_gbrt_input_ta_sp100:
    variables:
      ta: &variable_settings
        project: CMIP5
        mip: Amon
        field: T3M
        exp: historical
        start_year: 1979
        end_year: 2005
        preprocessor: sp100
        var_type: feature
        additional_datasets:
          - {dataset: ERA-Interim, project: OBS, type: reanaly, version: 1, tier: 3, var_type: prediction_input}
    scripts:
      mean: &mean
        script: gbrt/mean.py
        temporal_mean: True
        tag: T-SP_c
      trend: &trend
        script: gbrt/trend.py
        yearly_trend: True
        tag: T-SP_t

  # diag_gbrt_input_ta_ng100:
  #   variables:
  #     ta:
  #       <<: *variable_settings
  #       preprocessor: ng100
  #   scripts:
  #     mean:
  #       <<: *mean
  #       tag: T-NGlob_c
  #     trend:
  #       <<: *trend
  #       tag: T-NGlob_t

  # diag_gbrt_input_ta_trop250:
  #   variables:
  #     ta:
  #       <<: *variable_settings
  #       preprocessor: trop250
  #   scripts:
  #     mean:
  #       <<: *mean
  #       tag: T-Trop_c
  #     trend:
  #       <<: *trend
  #       tag: T-Trop_t

  # diag_gbrt_input_uajet_sh850:
  #   variables:
  #     uajet:
  #       <<: *variable_settings
  #       field: T0M
  #       preprocessor: noop
  #       derive: True
  #   scripts:
  #     mean:
  #       <<: *mean
  #       tag: U-Jet_c
  #     trend:
  #       <<: *trend
  #       tag: U-Jet_t

  diag_gbrt_input_mmstf:
    variables:
      va:
        <<: *variable_settings
        preprocessor: noop
      ps:
        <<: *variable_settings
        field: T2Ms
        preprocessor: noop
    scripts:
      mean:
        script: austral_jet/mmstf.ncl
        calc_type: mean
        tag: H-SH_c
      trend:
        script: austral_jet/mmstf.ncl
        calc_type: trend
        tag: H-SH_t

  diag_gbrt:
    description: Perform GBRT on input data.
    variables:
      uajet:
        project: CMIP5
        mip: Amon
        field: T0M
        exp: rcp45
        start_year: 2015
        end_year: 2034
        preprocessor: time_average
        derive: True
        var_type: label
        tag: UAJET
    scripts:
      gbrt:
        script: gbrt/single_gbrt_model.py
        ancestors: [
          'uajet',
          'diag_gbrt_input_*/mean',
          'diag_gbrt_input_*/trend',
        ]
        accept_only_scalar_data: True
        group_datasets_by_attributes: ['dataset', 'ensemble']
        parameters:
          learning_rate: 0.001
